project_id = "ecimeextrtqousziglgy"

[functions.sofar-ai-chat]
verify_jwt = false

[functions.sofar-ai-qualify]
verify_jwt = false

[functions.sofar-ai-roleplay]
verify_jwt = false

[functions.sofar-ai-sequences]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.legal-ai-analyze]
verify_jwt = false

[functions.library-scrape-project]
verify_jwt = false
