project_id = "ecimeextrtqousziglgy"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.elevenlabs-tts]
    verify_jwt = true
  [functions.legal-ai-analyze]
    verify_jwt = false
  [functions.library-scrape-project]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.sofar-ai-chat]
    verify_jwt = false
  [functions.sofar-ai-qualify]
    verify_jwt = false
  [functions.sofar-ai-roleplay]
    verify_jwt = false
  [functions.sofar-ai-sequences]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
