// GENERATED by emails/newsletters/build.mjs. Do not edit.
export type NewsletterLang = "en" | "fr";
export interface NewsletterIssueMeta {
  id: string;
  sequence: "onboarding" | "monthly";
  day: number | null;
  subject: Record<NewsletterLang, string>;
  preview: Record<NewsletterLang, string>;
  /** True when the body still contains [[placeholders]] to fill before sending. */
  template: boolean;
}
export const NEWSLETTER_ISSUES: NewsletterIssueMeta[] = [
  {
    "id": "01-onboarding-welcome",
    "sequence": "onboarding",
    "day": 0,
    "subject": {
      "en": "Welcome to Sofara, {{first_name}}. Here is how you earn.",
      "fr": "Bienvenue chez Sofara, {{first_name}}. Voici comment vous gagnez."
    },
    "preview": {
      "en": "You refer. We close. You earn up to 3% of the property value.",
      "fr": "Vous recommandez. Nous concluons. Vous gagnez jusqu'à 3 % de la valeur du bien."
    },
    "template": false
  },
  {
    "id": "02-onboarding-commissions",
    "sequence": "onboarding",
    "day": 2,
    "subject": {
      "en": "How your Sofara commission is calculated (with real numbers)",
      "fr": "Comment votre commission Sofara est calculée (avec de vrais chiffres)"
    },
    "preview": {
      "en": "Up to 3% of the property value. AED 21,000 to AED 600,000 per deal.",
      "fr": "Jusqu'à 3 % de la valeur du bien. De AED 21 000 à AED 600 000 par dossier."
    },
    "template": false
  },
  {
    "id": "03-onboarding-who-to-refer",
    "sequence": "onboarding",
    "day": 5,
    "subject": {
      "en": "The 5 people in your network who will buy in Dubai",
      "fr": "Les 5 profils de votre réseau qui achèteront à Dubaï"
    },
    "preview": {
      "en": "You already know them. Here is how to recognise them and what to say.",
      "fr": "Vous les connaissez déjà. Voici comment les reconnaître et quoi leur dire."
    },
    "template": false
  },
  {
    "id": "04-onboarding-dubai-facts",
    "sequence": "onboarding",
    "day": 8,
    "subject": {
      "en": "10 Dubai facts to answer any question in your network",
      "fr": "10 faits sur Dubaï pour répondre à toutes les questions de votre réseau"
    },
    "preview": {
      "en": "Tax, yields, fees, ownership, visa. The talk track, in one page.",
      "fr": "Fiscalité, rendements, frais, propriété, visa. L'argumentaire en une page."
    },
    "template": false
  },
  {
    "id": "05-onboarding-payment-plans",
    "sequence": "onboarding",
    "day": 12,
    "subject": {
      "en": "Off-plan and payment plans: the 3-minute version for your contacts",
      "fr": "Off-plan et plans de paiement : la version 3 minutes pour vos contacts"
    },
    "preview": {
      "en": "60/40, 70/30, post-handover. What each means and who it suits.",
      "fr": "60/40, 70/30, post-livraison. Ce que chacun signifie et à qui il convient."
    },
    "template": false
  },
  {
    "id": "06-onboarding-legal",
    "sequence": "onboarding",
    "day": 16,
    "subject": {
      "en": "What the law lets you do as an ambassador (and what it does not)",
      "fr": "Ce que la loi vous autorise à faire en tant qu'ambassadeur (et ce qu'elle interdit)"
    },
    "preview": {
      "en": "No licence needed, because you introduce and we transact. The five rules.",
      "fr": "Aucune licence nécessaire, car vous introduisez et nous concluons. Les cinq règles."
    },
    "template": false
  },
  {
    "id": "07-onboarding-ambassador-plus",
    "sequence": "onboarding",
    "day": 21,
    "subject": {
      "en": "Ambassador+: earn 10% on every deal your recruits close",
      "fr": "Ambassadeur+ : gagnez 10 % sur chaque dossier conclu par vos filleuls"
    },
    "preview": {
      "en": "One recruited ambassador. A second income line, for life of the account.",
      "fr": "Un ambassadeur recruté. Une deuxième ligne de revenus, pour toute la vie du compte."
    },
    "template": false
  },
  {
    "id": "08-onboarding-30-days",
    "sequence": "onboarding",
    "day": 30,
    "subject": {
      "en": "Your first 30 days at Sofara: the checklist",
      "fr": "Vos 30 premiers jours chez Sofara : la checklist"
    },
    "preview": {
      "en": "Eight actions. The ambassadors who do them close within the quarter.",
      "fr": "Huit actions. Les ambassadeurs qui les font concluent dans le trimestre."
    },
    "template": false
  },
  {
    "id": "11-monthly-market-pulse",
    "sequence": "monthly",
    "day": null,
    "subject": {
      "en": "Dubai market pulse, [[MONTH YEAR]]: the 3 numbers to quote this month",
      "fr": "Pouls du marché de Dubaï, [[MOIS ANNÉE]] : les 3 chiffres à citer ce mois-ci"
    },
    "preview": {
      "en": "Transactions, prices, off-plan share. Plus the one-line answer to \"is it too late?\"",
      "fr": "Transactions, prix, part de l'off-plan. Et la réponse en une ligne à « est-ce trop tard ? »"
    },
    "template": true
  },
  {
    "id": "12-monthly-developer-spotlight",
    "sequence": "monthly",
    "day": null,
    "subject": {
      "en": "Emaar, Sobha, DAMAC, Nakheel: which developer for which client",
      "fr": "Emaar, Sobha, DAMAC, Nakheel : quel promoteur pour quel client"
    },
    "preview": {
      "en": "The developer map our advisors use, and what each pays you.",
      "fr": "La carte des promoteurs utilisée par nos conseillers, et ce que chacun vous rapporte."
    },
    "template": false
  },
  {
    "id": "13-monthly-legal-corner",
    "sequence": "monthly",
    "day": null,
    "subject": {
      "en": "Legal corner: the 5 documents behind every Dubai purchase",
      "fr": "Rubrique juridique : les 5 documents derrière chaque achat à Dubaï"
    },
    "preview": {
      "en": "Reservation form, SPA, Oqood, escrow, title deed. Explained for your contacts.",
      "fr": "Formulaire de réservation, SPA, Oqood, escrow, titre de propriété. Expliqués pour vos contacts."
    },
    "template": false
  },
  {
    "id": "14-monthly-golden-visa",
    "sequence": "monthly",
    "day": null,
    "subject": {
      "en": "The Golden Visa argument: AED 2 million, 10 years, the whole family",
      "fr": "L'argument Golden Visa : AED 2 millions, 10 ans, toute la famille"
    },
    "preview": {
      "en": "The most powerful reason to buy in Dubai, and how to raise it without overselling.",
      "fr": "La raison la plus puissante d'acheter à Dubaï, et comment l'évoquer sans survendre."
    },
    "template": false
  },
  {
    "id": "15-monthly-reactivation",
    "sequence": "monthly",
    "day": null,
    "subject": {
      "en": "{{first_name}}, Sofara has changed since you joined. Here is what is new.",
      "fr": "{{first_name}}, Sofara a changé depuis votre inscription. Voici les nouveautés."
    },
    "preview": {
      "en": "Ambassador+, Pro tools, SofarAI, simulators. Your link still works.",
      "fr": "Ambassadeur+, outils Pro, SofarAI, simulateurs. Votre lien fonctionne toujours."
    },
    "template": false
  },
  {
    "id": "16-monthly-agent-handover",
    "sequence": "monthly",
    "day": null,
    "subject": {
      "en": "For real estate agents: your Dubai clients, closed by a licensed team, paid to you",
      "fr": "Pour les agents immobiliers : vos clients Dubaï, conclus par une équipe licenciée, payés à vous"
    },
    "preview": {
      "en": "No UAE licence, no office, no travel. Hand over the client, keep up to 3%.",
      "fr": "Pas de licence aux Émirats, pas de bureau, pas de déplacement. Confiez le client, gardez jusqu'à 3 %."
    },
    "template": false
  }
];
